include:
  - project: 'development/ci-common'
    file: 'common.yml'

################## Stage: prepare
prepare_gem:
  extends: .prepare_gem_template

################## Stage: test
rspec:
  extends: .rspec_template

################## Stage: security
bundle_audit:
  extends: .bundle_audit_template

################## Stages: build & upload
build_gem:
  extends: .build_gem_template

upload_gem:
  extends: .upload_gem_template
