include:
  - project: 'development/ci-common'
    file: 'build_gem.yml'

image: "${CI_REGISTRY}/devops/container-ruby/ruby-ci:v1"

stages:
  - security
  - build_gem
  - upload_gem

variables:
  PROXY: http://rubygems.prod.radar.lan
  ENV: test

before_script:
  - bundle install --jobs=$(nproc) --path=~/gems "${FLAGS[@]}"

bundle_audit:
  stage: security
  tags:
    - kubernetes
  script:
    - bundle exec bundle-audit check --update
  allow_failure: true

build_gem:
  extends: .build_gem

upload_gem:
  extends: .upload_gem

